const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const source = fs.readFileSync(path.join(__dirname, 'app.js'), 'utf8');
let checks = 0;
function test(name, fn) { fn(); checks += 1; console.log(`✓ ${name}`); }
function session(saved = new Map(), storageFails = false) {
  const handlers = {};
  const page = { innerHTML:'', insertAdjacentHTML(_p,markup){this.innerHTML+=markup;} };
  const document = { querySelector(s){return s==='#app'?page:null;}, querySelectorAll(){return[];}, addEventListener(k,fn){handlers[k]=fn;} };
  const context = vm.createContext({document,localStorage:{getItem:k=>saved.get(k)||null,setItem(k,v){if(storageFails)throw Error('Storage unavailable');saved.set(k,v);}},window:{scrollTo(){}},structuredClone,Date});
  vm.runInContext(source,context);
  return {page,saved,run(code){return vm.runInContext(code,context);},state(){return this.run('state');},click(action,extra={}){handlers.click({target:{closest(s){return s==='[data-action]'?{dataset:{action,...extra}}:null;}}});},
    input(field,value,update=false){this.field(update?{updateField:field}:{field},value);},
    field(dataset,value){const el={dataset,value,type:typeof value==='boolean'?'checkbox':'text',checked:value};for(const name of ['input','change'])handlers[name]({target:{closest(){return el;}}});},
    edit(id,field,value,update=false){this.field({noteField:field,id,update:String(update)},value);},
    key(key){handlers.keydown({key,preventDefault(){}});},
    reload(){return session(saved,storageFails);}
  };
}
function sampleSession(branch='feedback') {const s=session();s.click('start-sample');s.click('sample-question');if(branch!=='feedback')s.click('sample-choice',{branch});s.click('sample-answer');s.click('intro-next');return s;}
function complete() {const s=sampleSession();for(const id of ['E1','E2','E3','E4'])s.click('toggle-note',{id,status:'confirmed'});s.click('confirm-bottom');s.click('confirm-unknown');s.click('review-next');s.click('stance',{stance:'investigate'});s.click('save-action');return s;}
function guidanceCard(s){return s.run("comparisonRows().find(row=>row.title==='指导与反馈')");}

test('两种预置回答与自定义条件产生对应草稿，同义语序不改变反馈分支',()=>{
 const a=sampleSession();assert.equal(a.state().bottom.A,'pass');
 const b=sampleSession('ownership');assert.equal(b.state().bottom.A,'unknown');assert.match(b.state().unknown.text,/独立负责/);assert.doesNotMatch(b.state().actionDraft.text,/代码评审安排/);
 const c=session();c.click('start-sample');c.click('sample-question');c.input('bottom.rule','每周至少一次代码评审');c.click('sample-answer');assert.equal(c.state().sampleBranch,'feedback');assert.equal(c.state().bottom.A,'pass');
 const d=session();d.click('start-sample');d.click('sample-question');d.click('sample-choice',{branch:'custom'});d.input('bottom.rule','通勤不超过半小时');d.click('sample-answer');assert.equal(d.state().bottom.A,'unknown');assert.match(d.state().unknown.text,/通勤/);
});
test('首次梳理只确认一个未知，也能以验证行动完成',()=>{
 const s=session();s.click('start-manual');s.input('optionA','留下');s.input('optionB','去外地');s.click('intro-next');s.input('unknown.text','实际通勤多长？');s.click('confirm-unknown');s.click('review-next');assert.equal(s.state().view,'result');s.click('stance',{stance:'investigate'});s.input('actionDraft.text','实地体验一次通勤');s.click('save-action');assert.ok(s.state().firstCompletedAt);
});
test('依据编辑草稿与正式内容分离，空文本不能采用，来源和路径可修改',()=>{
 const s=sampleSession();s.click('toggle-note',{id:'E1',status:'confirmed'});s.click('edit-note',{id:'E1'});const old=s.state().notes[0].text;s.edit('E1','text','');assert.equal(s.state().notes[0].text,old);s.click('save-note',{id:'E1'});assert.ok(s.state().noteEdits.E1);assert.equal(s.state().noticeTarget,'note-E1');s.edit('E1','text','我的核实结果');s.edit('E1','side','B');s.edit('E1','source','本人核实');s.click('save-note',{id:'E1'});assert.equal(s.state().notes[0].side,'B');assert.equal(s.state().notes[0].source,'本人核实');assert.equal(s.state().notes[0].text,'我的核实结果');assert.equal(s.state().noteEdits.E1,undefined);
});
test('材料输入、维度选择与未完成编辑在刷新后恢复',()=>{
 let s=session();s.click('start-manual');s.input('optionA','A');s.input('optionB','B');s.click('intro-next');s.input('newNote.text','已经输入但没有提交');s.input('newNote.source','亲身经历');s.click('choose-topic',{scope:'manual',topic:'成本'});s=s.reload();assert.match(s.page.innerHTML,/已经输入但没有提交/);assert.match(s.page.innerHTML,/亲身经历/);assert.equal(s.state().newNote.topic,'成本');s.click('review-next');assert.equal(s.state().view,'review');s.click('add-note');const id=s.state().notes[0].id;s.click('edit-note',{id});s.edit(id,'text','编辑中的新内容');s=s.reload();assert.match(s.page.innerHTML,/编辑中的新内容/);s.click('review-next');assert.equal(s.state().noticeTarget,'review-next');
});
test('新增答复拆为两个维度，未确认不进入对比，采用后新信息优先且全部可展开',()=>{
 const s=complete();s.click('enter-update');s.click('load-sample-update');s.click('add-update-note');const added=s.state().updateDraft.notes.filter(n=>n.isNew);assert.equal(added.length,2);assert.equal(s.run('effectiveNotes(state.updateDraft).length'),4);for(const n of added)s.click('update-toggle-note',{id:n.id,status:'confirmed'});s.click('preview-update');assert.equal(s.state().view,'update-review');s.click('save-update');const row=guidanceCard(s);assert.match(row.B[0].text,/每周三/);assert.equal(row.B.length,2);assert.match(s.run("comparisonSide(state,comparisonRows().find(r=>r.title==='指导与反馈'),'B')"),/展开全部 2 条/);
});
test('只有已确认的新材料可替代旧依据，历史原文保留',()=>{
 const s=complete();s.click('enter-update');s.click('load-sample-update');s.click('add-update-note');const fresh=s.state().updateDraft.notes.find(n=>n.isNew&&n.topic==='指导与反馈');s.field({replaceNote:fresh.id,oldId:'E4'},true);assert.ok(s.run("effectiveNotes(state.updateDraft).some(n=>n.id==='E4')"));s.click('update-toggle-note',{id:fresh.id,status:'confirmed'});assert.ok(!s.run("effectiveNotes(state.updateDraft).some(n=>n.id==='E4')"));s.click('preview-update');s.click('save-update');assert.equal(s.state().notes.find(n=>n.id==='E4').status,'superseded');s.click('show-detail');assert.match(s.page.innerHTML,/已被替代/);assert.match(s.page.innerHTML,/相似团队的实习同学/);
});
test('底线或未知修改后取消确认，继续时明确确认或暂不纳入',()=>{
 const s=complete();s.click('enter-update');s.input('bottom.B','pass',true);assert.equal(s.state().updateDraft.bottom.confirmed,false);s.click('preview-update');assert.equal(s.state().view,'update');assert.match(s.page.innerHTML,/这几项还没确认/);s.click('condition-choice',{kind:'bottom',value:'confirm'});s.click('condition-continue');assert.equal(s.state().view,'update-review');s.click('return-update');s.input('unknown.resolved',true,true);assert.equal(s.state().updateDraft.unknown.confirmed,false);s.click('preview-update');s.click('condition-choice',{kind:'unknown',value:'confirm'});s.click('condition-continue');assert.equal(s.state().view,'update-review');s.click('save-update');assert.equal(s.run('derive().code'),'compare');
});
test('提示统一优先级：底线失败、关键未知、底线未知、信息不足、可比较',()=>{
 const s=complete();s.run("state.bottom.B='pass'");assert.equal(s.run('derive().code'),'question');assert.equal(s.run('guidanceLine()'),s.state().unknown.text);s.run("state.bottom.A='fail'");assert.equal(s.run('derive().code'),'bottom-fail');s.run("state.bottom.A='pass';state.bottom.B='unknown';state.unknown.resolved=true");assert.equal(s.run('derive().code'),'bottom-gap');s.run("state.bottom.B='pass';state.notes=[];state.bottom.support={}");assert.equal(s.run('derive().code'),'information-gap');
});
test('更新中未加入的输入不能被其它修改静默丢弃，刷新后仍在',()=>{
 let s=complete();s.click('enter-update');s.input('newText','还没有加入的新材料',true);s.input('context','新的背景',true);s.click('preview-update');assert.equal(s.state().view,'update');assert.equal(s.state().updateDraft.newText,'还没有加入的新材料');s=s.reload();assert.match(s.page.innerHTML,/还没有加入的新材料/);s.click('add-update-note');s.click('preview-update');assert.equal(s.state().view,'update-review');assert.match(s.page.innerHTML,/背景或回复期限已修改/);
});
test('取消更新有草稿保护，暂存后恢复更新预览',()=>{
 const s=complete();s.click('enter-update');s.input('context','新背景',true);s.click('cancel-update');assert.match(s.page.innerHTML,/放弃本次更新草稿/);assert.ok(s.state().updateDraft);s.click('keep-update');s.click('preview-update');s.click('park-update');s.click('resume');assert.equal(s.state().view,'update-review');s.click('return-update');s.click('cancel-update');s.click('discard-update');assert.equal(s.state().updateDraft,null);assert.notEqual(s.state().context,'新背景');
});
test('行动草稿刷新续接、历史行动和原来的立场日期可查看',()=>{
 let s=complete();const old=s.state().actions[0].text;s.click('revise-action');s.input('actionDraft.text','第二项行动的草稿');s.input('actionDraft.date','2026-10-03');s=s.reload();assert.match(s.page.innerHTML,/第二项行动的草稿/);assert.match(s.page.innerHTML,/保存新行动/);s.click('stance',{stance:'B'});s.click('save-action');assert.equal(s.state().actions.length,2);assert.match(s.page.innerHTML,/之前的 1 项行动/);assert.ok(s.page.innerHTML.includes(old));assert.match(s.page.innerHTML,/2026-10-03/);
});
test('常见错误都在对应按钮附近',()=>{
 const s=session();s.click('start-manual');s.click('intro-next');assert.ok(s.page.innerHTML.indexOf('panel-foot')<s.page.innerHTML.indexOf('请填写两条'));s.input('optionA','A');s.input('optionB','B');s.click('intro-next');s.click('review-next');assert.ok(s.page.innerHTML.indexOf('flow-bottom')<s.page.innerHTML.indexOf('至少确认一条'));s.input('unknown.text','问题');s.click('confirm-unknown');s.click('review-next');s.click('save-action');assert.equal(s.state().noticeTarget,'save-action');assert.ok(s.page.innerHTML.indexOf('action-form')<s.page.innerHTML.indexOf('请选择当前立场'));s.click('stance',{stance:'investigate'});s.input('actionDraft.text','问清楚');s.click('save-action');s.click('enter-update');s.click('add-update-note');assert.equal(s.state().noticeTarget,'add-update-note');assert.ok(s.page.innerHTML.indexOf('add-card')<s.page.innerHTML.indexOf('先写下一条'));
});
test('已有维度的常见别名能配对，通用未归类信息不强行合并',()=>{
 const s=session();s.click('start-manual');s.run("state.notes=[{id:'a',side:'A',topic:'指导安排',text:'a',status:'confirmed'},{id:'b',side:'B',topic:'指导与反馈',text:'b',status:'confirmed'},{id:'c',side:'A',text:'c',status:'confirmed'},{id:'d',side:'B',text:'d',status:'confirmed'}]");const rows=s.run('comparisonRows()');assert.equal(rows[0].A.length,1);assert.equal(rows[0].B.length,1);assert.equal(rows.length,3);
});
test('旧版本记录迁移后保留正文与行动，存储失败时不宣称已经保存',()=>{
 const saved=new Map([['decision-copilot:redcowork-prototype:v1',JSON.stringify({view:'result',notes:[{id:'a',side:'A',topic:'指导安排',text:'用户修改过的正文',status:'confirmed'}],actions:[{stance:'A',text:'旧行动',version:1}],actionDraft:{text:'尚未完成的行动'},firstCompletedAt:'2026-09-30',version:1})]]);
 const s=session(saved);assert.equal(s.state().notes[0].text,'用户修改过的正文');assert.equal(s.state().notes[0].topic,'指导与反馈');assert.match(s.page.innerHTML,/尚未完成的行动/);
 const broken=session(new Map(),true);broken.click('start-manual');assert.match(broken.page.innerHTML,/刷新后可能丢失/);assert.doesNotMatch(broken.page.innerHTML,/已暂存在/);
 const legacySample=new Map([['decision-copilot:redcowork-prototype:v1',JSON.stringify({mode:'sample',view:'intro',notes:[],introRevealed:true,sampleAnswer:'通勤半小时以内',bottom:{rule:'通勤半小时以内',A:'unknown',B:'unknown'},optionA:'A',optionB:'B'})]]);const legacy=session(legacySample);assert.equal(legacy.state().sampleBranch,'custom');assert.match(legacy.page.innerHTML,/不足以判断这项新条件/);
});
test('用户输入作为文本显示，不能插入页面元素',()=>{
 const s=sampleSession();s.input('optionA','<img src=x onerror=alert(1)>');s.click('review-back');assert.ok(!s.page.innerHTML.includes('<img src=x'));assert.match(s.page.innerHTML,/&lt;img/);
});
test('更严格、否定或复合条件不借用每周一次的证据，隐藏材料编辑能在刷新后恢复',()=>{
 const s=sampleSession();assert.equal(s.run("classifySample('每周两次代码评审')"),'custom');assert.equal(s.run("classifySample('不需要每周代码评审')"),'custom');assert.equal(s.run("classifySample('每周一次代码评审且每日指导')"),'custom');s.click('edit-note',{id:'E3'});s.edit('E3','text','刷新后继续的第三条材料');const restored=s.reload();assert.match(restored.page.innerHTML,/刷新后继续的第三条材料/);
});

test('漏点确认逐项选择，暂不纳入保留正文和结果提醒，再编辑后必须重新选择',()=>{
 let s=sampleSession();s.click('toggle-note',{id:'E1',status:'confirmed'});s.click('review-next');assert.equal(s.state().view,'review');assert.match(s.page.innerHTML,/这几项还没确认/);s.click('condition-continue');assert.equal(s.state().noticeTarget,'condition-gate');s.click('condition-choice',{kind:'bottom',value:'confirm'});s.click('condition-choice',{kind:'unknown',value:'defer'});s.click('condition-continue');assert.equal(s.state().view,'result');assert.equal(s.state().bottom.confirmed,true);assert.equal(s.state().unknown.confirmed,false);assert.match(s.page.innerHTML,/1 项条件草稿暂未纳入/);const question=s.state().unknown.text;s=s.reload();assert.equal(s.state().unknown.text,question);s.click('result-back');s.click('review-next');assert.equal(s.state().view,'result');s.click('result-back');s.input('unknown.text','B 的评审和指导安排具体是什么？');s.click('review-next');assert.match(s.page.innerHTML,/这几项还没确认/);
});
test('更新中的未确认修改允许有意识地暂不纳入，不会覆盖成已确认内容',()=>{
 const s=complete();s.click('enter-update');s.input('bottom.rule','每周至少两次评审',true);s.click('preview-update');s.click('condition-choice',{kind:'bottom',value:'defer'});s.click('condition-continue');assert.equal(s.state().view,'update-review');assert.match(s.page.innerHTML,/1 项条件草稿暂未纳入/);s.click('save-update');assert.equal(s.state().bottom.confirmed,false);assert.equal(s.state().bottom.rule,'每周至少两次评审');assert.equal(s.run('derive().code'),'question');
});
test('采用示例答复只提出变化，用户一键确认后底线和已回答问题同步更新',()=>{
 const s=complete();s.click('enter-update');s.click('load-sample-update');s.click('add-update-note');const n=s.state().updateDraft.notes.find(n=>n.sampleFacts?.weeklyReview);s.click('update-toggle-note',{id:n.id,status:'confirmed'});assert.equal(s.state().updateDraft.bottom.B,'unknown');assert.equal(s.state().updateDraft.unknown.resolved,false);assert.match(s.page.innerHTML,/这条答复是否解决了之前的问题/);s.click('apply-progress',{id:n.id,update:'true'});assert.equal(s.state().updateDraft.bottom.B,'pass');assert.equal(s.state().updateDraft.bottom.confirmed,true);assert.equal(s.state().updateDraft.unknown.resolved,true);assert.equal(s.state().bottom.B,'unknown');s.click('preview-update');s.click('save-update');assert.equal(s.run('derive().code'),'compare');assert.equal(s.state().actions.length,1);
});
test('复合问题只移除已明确回答的部分，更严格的底线仍不自动满足',()=>{
 const s=complete();s.click('enter-update');s.input('unknown.text','B 是否有稳定的代码评审，以及可独立负责的模块？',true);s.click('update-confirm-unknown');s.input('bottom.rule','每周两次代码评审',true);s.click('update-confirm-bottom');s.click('load-sample-update');s.click('add-update-note');const n=s.state().updateDraft.notes.find(n=>n.sampleFacts?.weeklyReview);s.click('update-toggle-note',{id:n.id,status:'confirmed'});s.click('apply-progress',{id:n.id,update:'true'});assert.equal(s.state().updateDraft.bottom.B,'unknown');assert.equal(s.state().updateDraft.unknown.resolved,false);assert.match(s.state().updateDraft.unknown.text,/可独立负责的模块/);assert.doesNotMatch(s.state().updateDraft.unknown.text,/代码评审/);assert.match(s.page.innerHTML,/部分进展/);
});
test('修改预置答复的正文或路径后，不能继续借用原有的事实提示',()=>{
 const s=complete();s.click('enter-update');s.click('load-sample-update');s.click('add-update-note');const n=s.state().updateDraft.notes.find(n=>n.sampleFacts?.weeklyReview);s.click('update-edit-note',{id:n.id});s.edit(n.id,'text','负责人说尚未确定评审安排',true);s.click('update-save-note',{id:n.id});assert.equal(s.state().updateDraft.notes.find(x=>x.id===n.id).sampleFacts,undefined);assert.equal(s.run(`progressProposal(state.updateDraft.notes.find(n=>n.id==='${n.id}'),state.updateDraft)`),null);assert.match(s.page.innerHTML,/核对条件和问题的进展/);
});
test('自由输入的答复可以由用户关联到条件与问题，部分回答保留剩余问题',()=>{
 const s=session();s.click('start-manual');s.input('optionA','留在当前团队');s.input('optionB','新团队');s.click('intro-next');s.input('bottom.rule','每周有固定反馈');s.click('confirm-bottom');s.input('unknown.text','B 的反馈频率和独立交付范围？');s.click('confirm-unknown');s.click('review-next');s.click('stance',{stance:'investigate'});s.input('actionDraft.text','向 B 负责人确认安排');s.click('save-action');s.click('enter-update');s.input('newText','负责人确认每周有一次反馈，交付范围还未定',true);s.click('add-update-note');const id=s.state().updateDraft.notes.at(-1).id;s.click('update-toggle-note',{id,status:'confirmed'});s.click('link-information',{id,update:'true'});s.field({progressField:'B',id,update:'true'},'pass');s.field({progressField:'question',id,update:'true'},'partial');s.click('apply-manual-progress',{id,update:'true'});assert.equal(s.state().noticeTarget,`note-${id}`);s.field({progressField:'remaining',id,update:'true'},'B 可以独立交付什么？');s.click('preview-update');assert.equal(s.state().view,'update');s.click('apply-manual-progress',{id,update:'true'});assert.equal(s.state().updateDraft.bottom.B,'pass');assert.equal(s.state().updateDraft.unknown.resolved,false);assert.equal(s.state().updateDraft.unknown.text,'B 可以独立交付什么？');s.click('preview-update');s.click('save-update');assert.equal(s.state().unknown.text,'B 可以独立交付什么？');
});
test('进入示例立即显示第一轮追问，回答后直接看三处变化并进入材料核对',()=>{
 const s=session();s.click('start-sample');assert.match(s.page.innerHTML,/AI · 预置追问/);assert.doesNotMatch(s.page.innerHTML,/看看 AI 会先问什么/);s.click('sample-answer');assert.match(s.page.innerHTML,/你的回答改变了这三处/);assert.match(s.page.innerHTML,/修改两条路径、背景或期限/);s.click('intro-next');assert.equal(s.state().view,'review');
});
test('示例与个人草稿独立保存，重置示例不会影响个人正文、更新或行动',()=>{
 let s=session();s.click('start-manual');s.input('optionA','我的个人路径A');s.input('optionB','我的个人路径B');s.input('context','个人背景');s.click('intro-next');s.input('newNote.text','我的材料草稿');s.click('home');assert.ok(s.page.innerHTML.indexOf('继续上次梳理')<s.page.innerHTML.indexOf('体验智能梳理'));s.click('start-sample');assert.equal(s.state().mode,'sample');assert.doesNotMatch(s.page.innerHTML,/开始一条新决策/);s.click('sample-answer');s=s.reload();assert.equal(s.state().mode,'sample');s.click('reset-sample');s.click('confirm-replace');assert.equal(s.state().introRevealed,false);s.click('home');s.click('resume');assert.equal(s.state().mode,'manual');assert.equal(s.state().optionA,'我的个人路径A');assert.equal(s.state().context,'个人背景');assert.equal(s.state().newNote.text,'我的材料草稿');s.click('clear-new-note');s.input('unknown.text','要验证的问题');s.click('confirm-unknown');s.click('review-next');s.click('stance',{stance:'investigate'});s.input('actionDraft.text','我的行动');s.click('save-action');s.click('enter-update');s.input('newText','个人更新草稿',true);s.click('home');s.click('start-sample');s.click('home');s.click('resume');assert.equal(s.state().actions[0].text,'我的行动');assert.equal(s.state().updateDraft.newText,'个人更新草稿');
});
test('手动录入先回答路径和正文，来源不捏造、未归类不冒充已进入具名维度',()=>{
 const s=session();s.click('start-manual');s.input('optionA','当前城市');s.input('optionB','另一座城市');s.click('intro-next');assert.match(s.page.innerHTML,/A · 当前城市/);assert.match(s.page.innerHTML,/补充来源和分类 · 选填/);assert.ok(s.page.innerHTML.indexOf('你具体知道什么')<s.page.innerHTML.indexOf('信息来源'));s.input('newNote.text','已核对的信息');s.click('add-note');assert.equal(s.state().notes[0].source,'来源未注明');assert.match(s.state().notice,/可稍后补充分类/);s.input('newNote.text','房租已确认');s.input('newNote.topic','成本');s.click('add-note');assert.match(s.state().notice,/A 的「成本」对比/);
});
test('撤回替代依据后不复活旧材料，有缺口提示和明确的重新核对入口',()=>{
 const s=complete();s.click('enter-update');s.click('load-sample-update');s.click('add-update-note');const n=s.state().updateDraft.notes.find(n=>n.sampleFacts?.weeklyReview);s.field({replaceNote:n.id,oldId:'E4'},true);s.click('update-toggle-note',{id:n.id,status:'confirmed'});s.click('preview-update');s.click('save-update');s.click('enter-update');s.click('toggle-old');s.click('update-toggle-note',{id:n.id,status:'rejected'});assert.equal(s.state().updateDraft.notes.find(n=>n.id==='E4').status,'superseded');assert.match(s.page.innerHTML,/本维度目前没有有效依据/);s.click('preview-update');s.click('save-update');assert.equal(s.run('derive().B.filter(n=>n.topic===\'指导与反馈\').length'),0);assert.match(s.page.innerHTML,/替代材料已撤回/);s.click('recheck-old',{id:'E4'});assert.equal(s.state().view,'update');assert.ok(s.state().updateDraft.noteEdits.E4);assert.equal(s.state().updateDraft.notes.find(n=>n.id==='E4').status,'superseded');s.click('update-save-note',{id:'E4'});assert.equal(s.state().updateDraft.notes.find(n=>n.id==='E4').status,'confirmed');
});
test('日期提示按本地日历比较，过去或晚于期限仍允许保存并显示提醒',()=>{
 const s=complete();assert.match(s.run("actionDateHint('2026-09-29','2026-09-28','2026-10-01')"),/已过去.*晚于回复期限/);assert.equal(s.run("actionDateHint('2026-10-01','2026-10-01','2026-10-01')"),'');assert.equal(s.run("localDay(new Date(2026,9,1,0,1))"),'2026-10-01');s.click('revise-action');s.click('stance',{stance:'investigate'});s.input('actionDraft.text','补记之前的行动');s.input('actionDraft.date','2020-01-01');s.click('save-action');assert.equal(s.state().actions.at(-1).date,'2020-01-01');assert.match(s.page.innerHTML,/计划日期已过去/);
});
test('重新生成页面时恢复展开状态、滚动和编辑焦点，不把关闭的折叠重新打开',()=>{
 const s=sampleSession();s.run(`globalThis.fakeDetails={dataset:{detailsKey:'source-materials'},open:true};globalThis.focusedAgain=false;globalThis.cursor=null;globalThis.focusEl={dataset:{field:'newNote.text'},selectionStart:2,selectionEnd:4,focus(){focusedAgain=true;},setSelectionRange(a,b){cursor=[a,b];}};document.querySelectorAll=selector=>selector==='details'?[fakeDetails]:[];document.querySelector=selector=>selector==='#app'?app:selector===focusIdentity(focusEl).selector?focusEl:null;document.activeElement=focusEl;window.scrollY=360;window.scrollTo=o=>{globalThis.scrollRestored=o.top;};rememberPresentation();document.activeElement=null;fakeDetails.open=false;`);
 // The stored snapshot is restored, without querying or driving a browser.
 s.run('renderedState=null;render();');assert.equal(s.run('fakeDetails.open'),true);assert.equal(s.run('scrollRestored'),360);assert.equal(s.run('focusedAgain'),true);assert.deepEqual(Array.from(s.run('cursor')),[2,4]);assert.equal(s.run('state.presentation.review.focus.start'),2);s.run('fakeDetails.open=false;rememberPresentation();render();');assert.equal(s.run('fakeDetails.open'),false);
});
test('撤回适用于两侧的替代材料时，仍有 A 侧依据也会提醒 B 侧的缺口',()=>{
 const s=session();s.click('start-manual');s.run("state.notes=[{id:'old',side:'both',topic:'时间',text:'旧的时长',status:'superseded'},{id:'replacement',side:'both',topic:'时间',text:'新的时长',status:'rejected',supersedes:['old']},{id:'A',side:'A',topic:'时间',text:'另有 A 的时长',status:'confirmed'}]");assert.equal(s.run('missingReplaced(state).length'),1);assert.equal(s.run('missingReplaced(state)[0].side'),'B');assert.match(s.run('resultCards(state)'),/路径 B 的「时间」替代材料已撤回/);
});

function answeredSession(){const s=complete();s.click('enter-update');s.click('load-sample-update');s.click('add-update-note');const n=s.state().updateDraft.notes.find(n=>n.sampleFacts?.weeklyReview);s.click('update-toggle-note',{id:n.id,status:'confirmed'});s.click('apply-progress',{id:n.id,update:'true'});s.click('preview-update');s.click('save-update');return{s,id:n.id};}
test('已确认答复改为没有评审后，B 和问题待复核、A 保持有效，保存和刷新不会恢复旧结论',()=>{
 let {s,id}=answeredSession();assert.equal(s.run('derive().code'),'compare');s.click('enter-update');s.click('update-edit-note',{id});s.edit(id,'text','负责人最新确认：近期没有代码评审安排。',true);s.click('update-save-note',{id});assert.match(s.run("bottomReview(state.updateDraft,'B')"),/依据/);assert.equal(s.run("bottomReview(state.updateDraft,'A')"),'');assert.ok(s.run('unknownReview(state.updateDraft)'));assert.equal(s.run('derive(state.updateDraft).code'),'review');s.click('preview-update');assert.match(s.page.innerHTML,/近期没有代码评审安排/);assert.match(s.page.innerHTML,/待复核/);s.click('save-update');assert.doesNotMatch(s.page.innerHTML,/两条路都满足了你确认的底线/);assert.equal(s.state().bottom.B,'pass');s=s.reload();assert.equal(s.run('derive().code'),'review');assert.match(s.page.innerHTML,/B 的底线判断待复核/);
});
test('重新核对必须明确选择状态；用户确认不满足后，结果和来源一致',()=>{
 const {s,id}=answeredSession();s.click('enter-update');s.click('update-edit-note',{id});s.edit(id,'text','近期没有代码评审安排',true);s.click('update-save-note',{id});s.click('update-confirm-bottom');assert.match(s.state().notice,/重新选择 B/);s.input('bottom.reviewChoices.B','fail',true);s.click('update-confirm-bottom');assert.equal(s.run("bottomReview(state.updateDraft,'B')"),'');assert.equal(s.state().updateDraft.bottom.B,'fail');s.input('unknown.reviewChoice','unresolved',true);s.click('update-confirm-unknown');assert.equal(s.run('unknownReview(state.updateDraft)'),'');s.click('preview-update');s.click('save-update');assert.equal(s.run('derive().code'),'bottom-fail');assert.match(s.page.innerHTML,/路径 B 暂不满足/);
});
test('撤回再采用关联材料仍需重新确认判断，不相关材料修改不会使 B 的评审判断失效',()=>{
 const {s,id}=answeredSession();s.click('enter-update');s.click('update-edit-note',{id:'E1'});s.edit('E1','text','A 的工作内容补充说明',true);s.click('update-save-note',{id:'E1'});assert.equal(s.run("bottomReview(state.updateDraft,'B')"),'');assert.equal(s.run('unknownReview(state.updateDraft)'),'');s.click('update-toggle-note',{id,status:'rejected'});assert.ok(s.run("bottomReview(state.updateDraft,'B')"));s.click('update-toggle-note',{id,status:'confirmed'});assert.ok(s.run("bottomReview(state.updateDraft,'B')"));
});
test('自定义依据关联后同样受复核约束，撤回一条材料不会清空其它侧的判断',()=>{
 const s=session();s.click('start-manual');s.input('optionA','上海');s.input('optionB','杭州');s.click('intro-next');s.input('newNote.text','上海已确认有住房补贴');s.click('add-note');const id=s.state().notes[0].id;s.input('bottom.rule','必须有住房补贴');s.input('bottom.A','pass');s.field({supportKind:'bottom',supportSide:'A',id,update:'false'},true);s.click('confirm-bottom');s.click('toggle-note',{id,status:'rejected'});assert.ok(s.run("bottomReview(state,'A')"));assert.equal(s.run("bottomReview(state,'B')"),'');assert.equal(s.run('derive().code'),'review');
});
test('未分类的两条月租由用户配对后，同卡展示两侧；仅分类不使已有关联判断失效',()=>{
 const s=session();s.click('start-manual');s.input('optionA','上海');s.input('optionB','杭州');s.click('intro-next');s.input('newNote.text','上海月租 3000 元');s.click('add-note');s.input('newNote.side','B');s.input('newNote.text','杭州月租 2000 元');s.click('add-note');const [a,b]=s.state().notes;s.input('unknown.text','两地月租差多少？');s.click('confirm-unknown');s.click('review-next');assert.match(s.page.innerHTML,/与另一条信息一起比较/);s.click('pair-information',{id:a.id});s.field({pairField:'partner'},b.id);assert.equal(s.run('ui.pairComparison.topic'),'租房成本');s.click('confirm-pair');const row=s.run("comparisonRows().find(r=>r.title==='租房成本')");assert.equal(row.A.length,1);assert.equal(row.B.length,1);assert.match(s.page.innerHTML,/上海月租 3000/);assert.match(s.page.innerHTML,/杭州月租 2000/);assert.equal(s.run('unknownReview(state)'),'');
});
test('完成后的配对进入具体变更预览，未确认前正式记录仍保留原分类',()=>{
 const s=session();s.click('start-manual');s.input('optionA','上海');s.input('optionB','杭州');s.click('intro-next');for(const [side,text]of[['A','上海月租3000'],['B','杭州月租2000']]){s.input('newNote.side',side);s.input('newNote.text',text);s.click('add-note');}s.click('review-next');s.click('stance',{stance:'investigate'});s.input('actionDraft.text','确认租房成本');s.click('save-action');const [a,b]=s.state().notes;s.click('pair-information',{id:a.id});s.field({pairField:'partner'},b.id);s.click('confirm-pair');assert.equal(s.state().view,'update-review');assert.equal(s.state().notes[0].topic,'其它重要信息');assert.match(s.page.innerHTML,/材料分类/);s.click('save-update');assert.equal(s.state().notes[0].topic,'租房成本');assert.equal(s.run('comparisonRows()[0].title'),'租房成本');assert.equal(s.run('actionNeedsReview(state.actions.at(-1))'),false);
});
test('关键问题与底线相关维度在默认两张卡中可见，更新后的相关依据也直接呈现',()=>{
 const s=complete();assert.equal(s.run('comparisonRows()[1].title'),'指导与反馈');assert.match(s.page.innerHTML,/每周安排一次代码评审/);const {s:updated}=answeredSession();assert.equal(updated.run('comparisonRows()[1].title'),'指导与反馈');assert.match(updated.page.innerHTML,/每周三参加代码评审/);
});
test('确认弹窗选择后保持同一按钮焦点和弹窗滚动位置，不再重置到开头',()=>{
 const s=sampleSession();s.click('toggle-note',{id:'E1',status:'confirmed'});s.click('review-next');s.run(`globalThis.modalFocusCalls=0;globalThis.chosenFocusCalls=0;globalThis.mockModal={scrollTop:123,focus(){modalFocusCalls++;}};globalThis.chosenButton={dataset:{action:'condition-choice',kind:'unknown',value:'defer'},focus(){chosenFocusCalls++;}};document.activeElement=chosenButton;document.querySelector=selector=>selector==='#app'?app:selector==='[role="dialog"]'||selector==='.confirm-modal'?mockModal:selector===focusIdentity(chosenButton).selector?chosenButton:null;`);s.click('condition-choice',{kind:'unknown',value:'defer'});assert.equal(s.run('chosenFocusCalls'),1);assert.equal(s.run('modalFocusCalls'),0);assert.equal(s.run('mockModal.scrollTop'),123);assert.equal(s.run('ui.conditionGate.choices.unknown'),'defer');assert.match(s.page.innerHTML,/已处理 1 \/ 2 项/);
});
test('更换 B 为研究生方案时旧 B 材料不参与，新旧名称和待复核内容在预览具体可见',()=>{
 const {s}=answeredSession();const A=s.state().pathIds.A,B=s.state().pathIds.B;s.click('enter-update');s.input('optionB','读一年制研究生',true);s.click('preview-update');assert.match(s.page.innerHTML,/这是改名称，还是换方案/);s.click('path-kind',{side:'B',value:'replace'});s.click('path-continue');assert.equal(s.state().view,'update-review');assert.match(s.page.innerHTML,/新团队的 AI 应用工程实习/);assert.match(s.page.innerHTML,/读一年制研究生/);assert.equal(s.run('derive(state.updateDraft).B.length'),0);assert.notEqual(s.state().updateDraft.pathIds.B,B);assert.equal(s.state().updateDraft.pathIds.A,A);assert.equal(s.run("bottomReview(state.updateDraft,'A')"),'');assert.ok(s.run("bottomReview(state.updateDraft,'B')"));s.click('save-update');assert.equal(s.run('derive().B.length'),0);s.click('enter-update');s.click('load-sample-update');assert.match(s.state().notice,/原实习方案/);
});
test('只调整路径名称保持身份和已核对材料；真正换方案后仍适用的材料需明确采用',()=>{
 const {s}=answeredSession();const B=s.state().pathIds.B;s.click('enter-update');s.input('optionB','B 团队 AI 实习',true);s.click('preview-update');s.click('path-kind',{side:'B',value:'rename'});s.click('path-continue');assert.equal(s.state().updateDraft.pathIds.B,B);assert.equal(s.run('derive(state.updateDraft).code'),'compare');s.click('save-update');s.click('enter-update');s.input('optionB','读研究生',true);s.click('preview-update');s.click('path-kind',{side:'B',value:'replace'});s.click('path-continue');assert.equal(s.run('derive(state.updateDraft).B.length'),0);s.click('return-update');s.click('keep-applicable',{id:'E2',side:'B',update:'true'});assert.ok(s.run("effectiveNotes(state.updateDraft).some(n=>n.id==='E2')"));assert.ok(s.run("bottomReview(state.updateDraft,'B')"));s.click('preview-update');assert.match(s.page.innerHTML,/用户确认仍适用于当前方案/);
});
test('更换适用于两侧材料的一侧方案，不影响另一侧材料与判断',()=>{
 const s=complete();s.click('enter-update');s.input('newSide','both',true);s.input('newTopic','时间',true);s.input('newText','两个团队都接受同样的三个月安排',true);s.click('add-update-note');const id=s.state().updateDraft.notes.at(-1).id;s.click('update-toggle-note',{id,status:'confirmed'});s.click('preview-update');s.click('save-update');s.click('enter-update');s.input('optionB','一年制研究生',true);s.click('preview-update');s.click('path-kind',{side:'B',value:'replace'});s.click('path-continue');assert.ok(s.run(`derive(state.updateDraft).A.some(n=>n.id==='${id}')`));assert.ok(!s.run(`derive(state.updateDraft).B.some(n=>n.id==='${id}')`));
});
test('问题解决后行动明显待复核，可确认继续或标记完成，历史正文保留',()=>{
 const {s}=answeredSession();assert.equal(s.run('actionNeedsReview(state.actions.at(-1))'),true);assert.match(s.page.innerHTML,/这项行动需要复核/);assert.match(s.page.innerHTML,/仍需继续/);s.click('continue-action');assert.equal(s.run('actionNeedsReview(state.actions.at(-1))'),false);const text=s.state().actions.at(-1).text;s.click('complete-action');assert.equal(s.state().actions.at(-1).status,'completed');assert.match(s.page.innerHTML,/上次行动 · 已完成/);assert.doesNotMatch(s.page.innerHTML,/这项行动需要复核/);s.click('revise-action');s.click('stance',{stance:'B'});s.input('actionDraft.text','约定下一步入职安排');s.click('save-action');assert.equal(s.state().actions.length,2);assert.match(s.page.innerHTML,/之前的 1 项行动/);assert.ok(s.page.innerHTML.includes(text));
});
test('只修改背景或不相关工作内容，不把评审行动误标为待复核',()=>{
 const s=complete();assert.equal(s.run('actionNeedsReview(state.actions.at(-1))'),false);s.click('enter-update');s.input('context','仅补充决策背景',true);s.click('preview-update');s.click('save-update');assert.equal(s.run('actionNeedsReview(state.actions.at(-1))'),false);s.click('enter-update');s.click('update-edit-note',{id:'E1'});s.edit('E1','text','A 的工作职责增加文档维护',true);s.click('update-save-note',{id:'E1'});s.click('preview-update');s.click('save-update');assert.equal(s.run('actionNeedsReview(state.actions.at(-1))'),false);
});
test('旧版已满足但答复已被改写的案例记录迁移后先待复核，不重现旧的满足结论',()=>{
 const {s,id}=answeredSession();s.run(`state.schemaVersion=3;delete state.bottom.support;delete state.bottom.pathRefs;delete state.unknown.support;delete state.unknown.pathRefs;const n=state.notes.find(n=>n.id==='${id}');n.text='近期没有代码评审安排';delete n.sampleFacts;delete n.progressReviewed;persist();`);const restored=s.reload();assert.equal(restored.run('derive().code'),'review');assert.match(restored.page.innerHTML,/旧记录|之前核实/);assert.doesNotMatch(restored.page.innerHTML,/两条路都满足了你确认的底线/);
});
test('更换方案后，旧答复不再提供原案例自动进展，历史替代缺口不冒充当前问题',()=>{
 const {s,id}=answeredSession();s.click('enter-update');s.input('optionB','读研究生',true);s.click('preview-update');s.click('path-kind',{side:'B',value:'replace'});s.click('path-continue');s.run(`{const n=state.updateDraft.notes.find(n=>n.id==='${id}');n.isNew=true;delete n.progressReviewed;}`);assert.equal(s.run(`progressProposal(state.updateDraft.notes.find(n=>n.id==='${id}'),state.updateDraft)`),null);assert.equal(s.run(`manualProgressPrompt(state.updateDraft.notes.find(n=>n.id==='${id}'),state.updateDraft,true)`),'');s.run(`{const d=state.updateDraft,n=d.notes.find(n=>n.id==='${id}');n.status='rejected';n.supersedes=['E4'];d.notes.find(n=>n.id==='E4').status='superseded';}`);assert.equal(s.run('missingReplaced(state.updateDraft).length'),0);s.click('keep-applicable',{id,side:'B',update:'true'});assert.equal(s.run(`progressProposal(state.updateDraft.notes.find(n=>n.id==='${id}'),state.updateDraft)`),null);
});
test('已排除的历史替代材料不能再次覆盖用户确认适用于新方案的旧信息',()=>{
 const s=complete();s.click('enter-update');s.click('load-sample-update');s.click('add-update-note');const id=s.state().updateDraft.notes.find(n=>n.sampleFacts?.weeklyReview).id;s.field({replaceNote:id,oldId:'E4'},true);s.click('update-toggle-note',{id,status:'confirmed'});s.click('preview-update');s.click('save-update');assert.equal(s.state().notes.find(n=>n.id==='E4').status,'superseded');s.click('enter-update');s.input('optionB','读研究生',true);s.click('preview-update');s.click('path-kind',{side:'B',value:'replace'});s.click('path-continue');s.click('keep-applicable',{id:'E4',side:'B',update:'true'});s.click('save-update');assert.equal(s.state().notes.find(n=>n.id==='E4').status,'confirmed');assert.ok(s.run("derive().B.some(n=>n.id==='E4')"));
});
function changePathInUpdate(s,name,kind='replace'){
 if(s.state().view==='update-review')s.click('return-update');s.input('optionB',name,true);s.click('preview-update');s.click('path-kind',{side:'B',value:kind});assert.match(s.page.innerHTML,/确认变更方式/);s.click('path-continue');assert.equal(s.state().view,'update-review');
}
test('同一次更新中研究生再换创业，每次使用独立方案身份，中间学费不进入创业对比',()=>{
 let s=complete();const original=s.state().pathIds.B;s.click('enter-update');changePathInUpdate(s,'读研究生');const graduate=s.state().updateDraft.pathIds.B;assert.notEqual(graduate,original);s.click('return-update');s.input('newText','研究生每年学费 8 万元',true);s.input('newTopic','教育成本',true);s.click('add-update-note');const tuition=s.state().updateDraft.notes.at(-1).id;s.click('update-toggle-note',{id:tuition,status:'confirmed'});assert.ok(s.run(`derive(state.updateDraft).B.some(n=>n.id==='${tuition}')`));changePathInUpdate(s,'回家创业');const business=s.state().updateDraft.pathIds.B;assert.notEqual(business,graduate);assert.notEqual(business,original);assert.equal(s.run('derive(state.updateDraft).B.length'),0);assert.doesNotMatch(s.run('resultCards(state.updateDraft)'),/学费 8 万元/);assert.match(s.page.innerHTML,/学费 8 万元/);assert.match(s.page.innerHTML,/原方案材料，未纳入当前对比/);s.click('save-update');s=s.reload();assert.equal(s.state().pathIds.B,business);assert.equal(s.run('derive().B.length'),0);assert.equal(s.state().notes.find(n=>n.id===tuition).pathIds.B,graduate);
});
test('中间方案更名保留其材料，撤回待确认的名称修改恢复上次状态，后续换方案仍重新隔离',()=>{
 const s=complete();s.click('enter-update');changePathInUpdate(s,'读研究生');const graduate=s.state().updateDraft.pathIds.B;s.click('return-update');s.input('newText','研究生学费八万元',true);s.click('add-update-note');const id=s.state().updateDraft.notes.at(-1).id;s.click('update-toggle-note',{id,status:'confirmed'});s.input('optionB','另一个待确认名称',true);s.input('optionB','读研究生',true);assert.equal(s.state().updateDraft.pathIds.B,graduate);assert.equal(s.run('pendingPathChanges(state.updateDraft).length'),0);changePathInUpdate(s,'一年制研究生','rename');assert.equal(s.state().updateDraft.pathIds.B,graduate);assert.ok(s.run(`derive(state.updateDraft).B.some(n=>n.id==='${id}')`));assert.match(s.page.innerHTML,/更换方案/);changePathInUpdate(s,'新团队的 AI 应用工程实习');assert.notEqual(s.state().updateDraft.pathIds.B,s.state().pathIds.B);assert.notEqual(s.state().updateDraft.pathIds.B,graduate);assert.equal(s.run('derive(state.updateDraft).B.length'),0);s.click('save-update');assert.equal(s.state().optionB,'新团队的 AI 应用工程实习');assert.equal(s.run('derive().B.length'),0);
});
test('底线改写后不沿用旧满足值，暂不纳入后退出结果、复核与对比，历史明确对应原条件',()=>{
 let {s,id}=answeredSession();s.click('enter-update');s.click('update-edit-note',{id});s.edit(id,'text','近期没有代码评审安排',true);s.click('update-save-note',{id});assert.ok(s.run("bottomReview(state.updateDraft,'B')"));s.input('bottom.rule','每周至少两次代码评审',true);assert.equal(s.state().updateDraft.bottom.A,'unknown');assert.equal(s.state().updateDraft.bottom.B,'unknown');assert.equal(s.state().updateDraft.bottom.lastConfirmed.rule,'至少每周一次代码评审');s.input('unknown.text','',true);s.click('preview-update');s.click('condition-choice',{kind:'bottom',value:'defer'});s.click('condition-continue');assert.equal(s.state().view,'update-review');assert.equal(s.run('derive(state.updateDraft).code'),'compare');assert.equal(s.run('judgmentReviews(state.updateDraft).length'),0);assert.equal(s.run("comparisonRows(state.updateDraft).filter(r=>r.kind==='bottom').length"),0);assert.doesNotMatch(s.run('resultCards(state.updateDraft)'),/每周至少两次|compare-value-pass/);s.click('save-update');s=s.reload();assert.equal(s.state().bottom.confirmed,false);assert.match(s.page.innerHTML,/1 项条件草稿暂未纳入/);assert.doesNotMatch(s.page.innerHTML,/每周至少两次|两条路都满足了/);s.click('review-excluded');assert.match(s.page.innerHTML,/原条件：至少每周一次代码评审/);assert.match(s.page.innerHTML,/这些判断对应原条件/);
});
test('没有改写内容的过期底线也能暂不纳入，不继续驱动当前复核或卡片',()=>{
 const {s,id}=answeredSession();s.click('enter-update');s.click('update-toggle-note',{id,status:'rejected'});s.input('bottom.B','unknown',true);s.input('unknown.text','',true);assert.ok(s.run("bottomReview(state.updateDraft,'B')"));s.click('preview-update');s.click('condition-choice',{kind:'bottom',value:'defer'});s.click('condition-continue');assert.equal(s.state().view,'update-review');assert.equal(s.run('judgmentReviews(state.updateDraft).length'),0);assert.equal(s.run('derive(state.updateDraft).code'),'compare');assert.equal(s.run("comparisonRows(state.updateDraft).some(r=>r.kind==='bottom')"),false);s.click('save-update');assert.doesNotMatch(s.page.innerHTML,/B 的底线判断待复核/);
});
test('排除的条件不增加维度优先级，未纳入的问题草稿不作为行动依据',()=>{
 const s=complete();s.run("state.bottom.confirmed=false;state.unknown.confirmed=false;state.focusTopics=[];");const before=s.run("actionBasis({stance:'investigate',text:'核对两侧材料'},state).question");assert.equal(before,'');assert.equal(s.run("rowPriority(state,comparisonRows().find(r=>r.title==='指导与反馈'))"),10);s.input('unknown.text','仅存在草稿中的新问题');assert.equal(s.run("actionBasis({stance:'investigate',text:'核对两侧材料'},state).question"),'');
});
test('行动完成后停止过期日期提醒，进入历史仍保留完成时间，新行动替代未完成行动也有状态',()=>{
 let s=complete();s.click('revise-action');s.click('stance',{stance:'investigate'});s.input('actionDraft.text','先询问负责人');s.input('actionDraft.date','2020-01-01');s.click('save-action');assert.match(s.page.innerHTML,/计划日期已过去/);s.click('complete-action');const done=s.state().actions.at(-1),completedAt=done.completedAt;assert.match(s.page.innerHTML,/完成于/);assert.doesNotMatch(s.page.innerHTML,/计划日期已过去|计划日期晚于/);s.click('revise-action');s.click('stance',{stance:'B'});s.input('actionDraft.text','确认入职日期');s.click('save-action');assert.equal(s.state().actions.at(-2).status,'completed');assert.equal(s.state().actions.at(-2).completedAt,completedAt);const history=s.run('history()');assert.match(history,/已完成/);assert.match(history,/完成于/);assert.match(history,/被新行动替代/);assert.match(history,/替代于/);assert.match(history,/原计划日期：2020-01-01/);assert.doesNotMatch(s.page.innerHTML,/计划日期已过去/);s=s.reload();assert.equal(s.state().actions.at(-2).completedAt,completedAt);assert.match(s.run('history()'),/已完成/);
});
test('旧版暂存的方案更换在迁移后重新核对，材料保留但不默认进入新确认方案',()=>{
 let s=complete();s.click('enter-update');changePathInUpdate(s,'读研究生');const graduate=s.state().updateDraft.pathIds.B;s.click('return-update');s.input('newText','研究生学费八万元',true);s.click('add-update-note');const id=s.state().updateDraft.notes.at(-1).id;s.click('update-toggle-note',{id,status:'confirmed'});s.run('state.schemaVersion=4;persist();');s=s.reload();assert.equal(s.state().schemaVersion,6);assert.equal(s.state().updateDraft.notes.find(n=>n.id===id).text,'研究生学费八万元');assert.equal(s.run('pendingPathChanges(state.updateDraft).length'),1);s.click('preview-update');assert.match(s.page.innerHTML,/旧版暂存的方案变更需再核对一次/);s.click('path-kind',{side:'B',value:'replace'});s.click('path-continue');assert.notEqual(s.state().updateDraft.pathIds.B,graduate);assert.equal(s.run('derive(state.updateDraft).B.length'),0);
});
test('旧版已暂不纳入的新底线迁移后不复活旧满足值，有原记录时历史对应原条件',()=>{
 let s=complete();s.click('enter-update');s.run("state.schemaVersion=4;delete state.bottom.lastConfirmed;const b=state.updateDraft.bottom;delete b.lastConfirmed;b.rule='每周至少两次代码评审';b.A='pass';b.confirmed=false;b.deferredFingerprint=conditionFingerprint('bottom',b);persist();");s=s.reload();assert.equal(s.state().updateDraft.bottom.A,'unknown');assert.equal(s.state().updateDraft.bottom.lastConfirmed.rule,'至少每周一次代码评审');assert.equal(s.run("comparisonRows(state.updateDraft).some(r=>r.kind==='bottom')"),false);s.click('preview-update');assert.equal(s.state().view,'update-review');assert.doesNotMatch(s.run('resultCards(state.updateDraft)'),/每周至少两次代码评审/);
});

test('新增材料前必须确认方案变更，已有输入保留，确认后材料属于新方案',()=>{
 const s=complete();s.click('enter-update');const before=s.state().updateDraft.notes.length,original=s.state().updateDraft.pathIds.B;s.input('optionB','读研究生',true);assert.match(s.run('addForm(true)'),/先确认方案变更/);assert.match(s.run('addForm(true)'),/material-fields" disabled/);s.input('newText','学费每年 8 万元',true);s.click('add-update-note');assert.equal(s.state().updateDraft.notes.length,before);assert.equal(s.state().updateDraft.newText,'学费每年 8 万元');assert.match(s.page.innerHTML,/这是改名称，还是换方案/);s.click('path-kind',{side:'B',value:'replace'});assert.equal(s.state().updateDraft.pathIds.B,original);s.click('path-continue');assert.equal(s.state().view,'update');assert.equal(s.state().updateDraft.notes.length,before);assert.equal(s.state().updateDraft.newText,'学费每年 8 万元');assert.equal(s.run('pendingPathChanges(state.updateDraft).length'),0);assert.match(s.page.innerHTML,/B · 读研究生/);s.click('add-update-note');const n=s.state().updateDraft.notes.at(-1);s.click('update-toggle-note',{id:n.id,status:'confirmed'});assert.notEqual(n.pathIds.B,original);assert.equal(n.pathIds.B,s.state().updateDraft.pathIds.B);assert.ok(s.run(`effectiveNotes(state.updateDraft).some(n=>n.id==='${n.id}')`));assert.ok(!s.run("effectiveNotes(state.updateDraft).some(n=>n.id==='E2')"));
});
test('只更名后保留原材料；首次流程新增也受方案确认约束',()=>{
 const s=sampleSession();s.click('toggle-note',{id:'E2',status:'confirmed'});const original=s.state().pathIds.B,count=s.state().notes.length;s.input('optionB','AI 工程实习新名称');s.input('newNote.side','B');s.input('newNote.text','新的确认信息');s.click('add-note');assert.equal(s.state().notes.length,count);s.click('path-kind',{side:'B',value:'rename'});s.click('path-continue');assert.equal(s.state().view,'review');assert.equal(s.state().pathIds.B,original);s.click('add-note');assert.equal(s.state().notes.at(-1).pathIds.B,original);assert.ok(s.run("effectiveNotes(state).some(n=>n.id==='E2')"));assert.ok(s.run("effectiveNotes(state).some(n=>n.text==='新的确认信息')"));
});
test('变更方式尚未最终确认时退出或刷新不会开放录入，也不改写方案身份',()=>{
 let s=complete();s.click('enter-update');const original=s.state().updateDraft.pathIds.B;s.input('optionB','读研究生',true);s.click('confirm-material-paths',{update:'true'});s.click('path-kind',{side:'B',value:'replace'});s.run(`const fakeDialog={focus(){},querySelectorAll(){return[];}};document.querySelector=selector=>selector==='#app'?app:selector==='[role="dialog"]'&&ui.pathGate?fakeDialog:null;`);s.key('Escape');assert.equal(s.run('ui.pathGate'),null);assert.equal(s.state().updateDraft.pathIds.B,original);assert.equal(s.run('pendingPathChanges(state.updateDraft).length'),1);s.click('confirm-material-paths',{update:'true'});s.click('path-kind',{side:'B',value:'replace'});s=s.reload();assert.equal(s.run('pendingPathChanges(state.updateDraft).length'),1);assert.equal(s.state().updateDraft.pathIds.B,original);assert.match(s.page.innerHTML,/先确认方案变更/);s.click('confirm-material-paths',{update:'true'});s.click('path-back');assert.equal(s.state().view,'update');assert.equal(s.run('pendingPathChanges(state.updateDraft).length'),1);s.click('confirm-material-paths',{update:'true'});s.click('path-kind',{side:'B',value:'replace'});s.click('path-continue');assert.notEqual(s.state().updateDraft.pathIds.B,original);
});
test('关联依据修改时底线与问题按钮立即同步状态和原因，再确认及刷新一致',()=>{
 let s=complete();s.click('enter-update');s.run(`const buttons={bottom:{textContent:'',classList:{toggle(name,value){this[name]=value;}}},unknown:{textContent:'',classList:{toggle(name,value){this[name]=value;}}}},hints={bottom:{},unknown:{}};document.querySelector=selector=>selector==='#app'?app:selector.includes('confirm-bottom')?buttons.bottom:selector.includes('confirm-unknown')?buttons.unknown:selector.includes('data-confirmation-hint="bottom"')?hints.bottom:selector.includes('data-confirmation-hint="unknown"')?hints.unknown:null;`);s.field({supportKind:'bottom',supportSide:'A',id:'E1',update:'true'},true);assert.equal(s.state().updateDraft.bottom.confirmed,false);assert.equal(s.run('buttons.bottom.textContent'),'重新确认底线');assert.equal(s.run('buttons.bottom.classList["btn-approve"]'),true);assert.match(s.run('hints.bottom.textContent'),/关联依据已调整/);assert.equal(s.run('hints.bottom.hidden'),false);s.field({supportKind:'unknown',supportSide:'both',id:'E4',update:'true'},true);assert.equal(s.run('buttons.unknown.textContent'),'重新确认问题');assert.equal(s.state().updateDraft.unknown.confirmed,false);assert.match(s.run('hints.unknown.textContent'),/关联依据已调整/);s=s.reload();s.click('toggle-conditions');assert.match(s.page.innerHTML,/重新确认底线/);assert.match(s.page.innerHTML,/重新确认问题/);s.click('preview-update');assert.match(s.page.innerHTML,/这几项还没确认/);s.click('condition-back');s.click('update-confirm-bottom');s.click('update-confirm-unknown');assert.equal(s.state().updateDraft.bottom.confirmed,true);assert.equal(s.state().updateDraft.unknown.confirmed,true);assert.equal(s.state().updateDraft.bottom.confirmationReason,undefined);assert.equal(s.state().updateDraft.unknown.confirmationReason,undefined);assert.doesNotMatch(s.page.innerHTML,/关联依据已调整/);
});
test('暂不纳入后再调整关联依据，继续时重新提示，不沿用之前的跳过选择',()=>{
 const s=complete();s.click('enter-update');s.field({supportKind:'unknown',supportSide:'both',id:'E4',update:'true'},true);s.click('preview-update');s.click('condition-choice',{kind:'unknown',value:'defer'});s.click('condition-continue');assert.equal(s.state().view,'update-review');assert.ok(s.state().updateDraft.unknown.deferredFingerprint);s.click('return-update');s.field({supportKind:'unknown',supportSide:'both',id:'E4',update:'true'},false);assert.equal(s.state().updateDraft.unknown.deferredFingerprint,undefined);s.click('preview-update');assert.match(s.page.innerHTML,/这几项还没确认/);
});
function pairingSession(){const s=complete();s.run("state.notes.find(n=>n.id==='E1').topic='其它重要信息';persist();render();");return s;}
function pairingKeyboard(s){s.run(`let returnedFocus=0,lastScroll=null;const pairTrigger={dataset:{action:'pair-information',id:'E1'},focus(){returnedFocus++;}},fakeDialog={focus(){},querySelectorAll(){return[];}};window.scrollY=410;window.scrollTo=arg=>{lastScroll=arg.top;};document.querySelector=selector=>selector==='#app'?app:selector==='[role="dialog"]'&&ui.pairComparison?fakeDialog:selector==='.confirm-modal'&&ui.pairComparison?fakeDialog:selector==='[data-action="pair-information"][data-id="E1"]'?pairTrigger:null;`);}
test('Escape 与稍后再分均清除空配对更新，回到结果并恢复入口焦点和位置',()=>{
 for(const escape of [true,false]){let s=pairingSession();pairingKeyboard(s);s.click('pair-information',{id:'E1'});assert.ok(s.state().updateDraft);if(escape)s.key('Escape');else s.click('cancel-pair');assert.equal(s.state().updateDraft,null);assert.equal(s.state().view,'result');assert.equal(s.run('ui.pairComparison'),null);assert.equal(s.run('returnedFocus'),1);assert.equal(s.run('lastScroll'),410);s=s.reload();assert.equal(s.state().updateDraft,null);s.click('home');s.click('start-sample');assert.equal(s.state().view,'result');}
});
test('取消配对保留已有更新与未加入的材料，不清除有内容的临时草稿',()=>{
 const existing=pairingSession();existing.click('enter-update');existing.input('context','已有更新',true);existing.input('newText','还没加入的信息',true);pairingKeyboard(existing);existing.click('pair-information',{id:'E1'});existing.key('Escape');assert.ok(existing.state().updateDraft);assert.equal(existing.state().updateDraft.context,'已有更新');assert.equal(existing.state().updateDraft.newText,'还没加入的信息');assert.equal(existing.state().view,'update');const created=pairingSession();pairingKeyboard(created);created.click('pair-information',{id:'E1'});created.input('newText','需要保留的输入',true);created.key('Escape');assert.ok(created.state().updateDraft);assert.equal(created.state().updateDraft.newText,'需要保留的输入');
});

test('方案变更待确认时载入原示例答复也先核对，不把旧岗位答复归给新方案',()=>{
 const s=complete();s.click('enter-update');s.input('optionB','读研究生',true);s.click('load-sample-update');assert.equal(s.state().updateDraft.newText,'');assert.match(s.page.innerHTML,/这是改名称，还是换方案/);s.click('path-kind',{side:'B',value:'replace'});s.click('path-continue');s.click('load-sample-update');assert.equal(s.state().updateDraft.newText,'');assert.match(s.state().notice,/示例答复属于原实习方案/);
});

console.log(`完成 ${checks} 项交互回归检查（状态与页面内容；不包含实际浏览器排版）。`);
